### ISSUE TITLE
As a System Admin I want to add technology Admin to a Technology

### ISSUE THREAD

**Issue by Panthro** [SkillTracker/skilltracker#10]

**Comment by Panthro** [comment]
Review what? there are no commits referenced, no funcionalities, nothing. :)

**Comment by paracuenta** [comment]
It was an error :), its not done

**Comment by silet11** [comment]
The admin can access to Technologies page. Is possible to create or edit a Technology and as you can see in the photo, some users may be assigned as a technology admin;
![assign tech admin](https://cloud.githubusercontent.com/assets/16286118/11951532/d502c730-a891-11e5-9d27-81c2a561e553.png)
