### ISSUE TITLE
As a User I want to List technology courses

### ISSUE THREAD

**Issue by Panthro** [SkillTracker/skilltracker#14]

**Comment by silet11** [comment]
We created the page listing courses for a user. The URL is: http://localhost:3000/#/dashboard/courses
![courses](https://cloud.githubusercontent.com/assets/16286118/11951162/f056e884-a88e-11e5-8f51-6da9cb72658f.png)

**Comment by Panthro** [comment]
That was a misinterpretation of the task.

If you read again the user story, it states:
As a User I want to List __technology__ courses 

Not User's courses, not courses by itself, it was supposed to be the list of the courses from a given technology.

This meant: given a technology, as a user I want to be able to list its courses.

**Comment by silet11** [comment]
![dashboard](https://cloud.githubusercontent.com/assets/16286118/11994306/339e9b56-aa3c-11e5-827d-c63fcc9ff738.JPG)
