### ISSUE TITLE
Define database model

### ISSUE THREAD

**Issue by Panthro** [SkillTracker/skilltracker#3]
Entities:
 - [x] Technology
 - [x] Course
 - [ ] Tag
 - [x] User

**Comment by Panthro** [comment]
The idea of this task is to define every property of every entity. So we can start creating the database model using jhipster entity subgenerator

**Comment by Ricard** [comment]
Finally, we defined the model with: Course, Technology and Enrolment.
User and Role are created by JHipster.
Tag is out of sprint scope.

The UML will be commited and the issue closed
