### ISSUE TITLE
better home screen

### ISSUE THREAD

**Issue by Panthro** [SkillTracker/skilltracker#35]
The home screen has information about jhipster, we should remove it and make it look more like a professional app.

- [ ] Find a new image to replace the jhipster
- [ ] Write a welcoming description about the app
- [ ] point to links of the login, dashboard, etc, etc, etc

**Comment by Panthro** [comment]
this is related to #34, but this is more about content while #34 is more about style and look and feel

**Comment by Ricard** [comment]
I think it is related to #34 and #44 that was closed by @DavydBR.
Close it if you are OK.

**Comment by DavydBR** [comment]
Yes, I think that the issues #34,#35 and #44 are related. I've made the changes, attached screenshots of the links that still had to make.
![loged](https://cloud.githubusercontent.com/assets/16334265/12115268/07326a6a-b3b1-11e5-939b-0e1b9c291f54.JPG)
![welcome](https://cloud.githubusercontent.com/assets/16334265/12115269/07347238-b3b1-11e5-82bf-936cb907f225.jpg)
