### ISSUE TITLE
Remove common initial users from load files

### ISSUE THREAD

**Issue by Panthro** [SkillTracker/skilltracker#36]
Check the file:

https://github.com/SkillTracker/skilltracker/blob/master/src/main/resources/config/liquibase/users.csv

It contains the users to be loaded to the database initially.

Change the users so it makes sense for the app, as well as passwords.

**Comment by Ricard** [comment]
We updated the users liquid database initialization file.
The users and passwords are sent by e-mail to all the team.

**Comment by Panthro** [comment]
first: why adding more common users to the file when the task was to remove the common users?

If any of you ever leaves the project, we'll have a list of users hardcoded that will be always there.

If someone forks the repository, the person will automatically get those new users. That's not a clean solution (also was not a clear, request, so I'm the one to blame in this case).

Please, remove all unnecessary users, change admin name to something more related to the project.

The initial load should only contain:
 - anonymous (required for internal things in spring security)
 - admin (with another name, can be skilltracker)
