### ISSUE TITLE
As a System Admin I want to Create a Technology

### ISSUE THREAD

**Issue by Panthro** [SkillTracker/skilltracker#8]

**Comment by Panthro** [comment]
no links to commits or functionalities nor screenshots or anything. =) I need information to review to approve the issue :-1:

**Comment by paracuenta** [comment]
As System Admin, we can see on navigation bar entities menu (but not as normal user).
On entities menu, we can select technology submenu, then we enter on administration panel of technologies. Here we can create new technology.

**Comment by Panthro** [comment]
Ok, I'm closing this one because we didn't setup the "Definition of Ready" nor "Definition of Done" heheh ;)
